package edu.dsoft.gui;

import javax.swing.*;
import java.awt.*;

public class CurrencyExchangePanel {
    private JPanel panelExchangePanel;
    private JPanel firstCurrencyPanel;
    private JPanel panelSwap;
    private JPanel secondCurrencyPanel;
    private JTextField fieldFirstAmount;
    private JButton btnExchange;
    private JPanel panelNorth;
    private JLabel labelFirstAmount;
    private JPanel panelSecondNorth;
    private JTextField fieldSecondAmount;
    private JButton btnSwapCurrencies;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelExchangePanel = new JPanel();
        panelExchangePanel.setLayout(new FlowLayout(FlowLayout.LEADING, 0, 0));
        firstCurrencyPanel = new JPanel();
        firstCurrencyPanel.setLayout(new BorderLayout(0, 0));
        panelExchangePanel.add(firstCurrencyPanel);
        fieldFirstAmount = new JTextField();
        fieldFirstAmount.setColumns(10);
        firstCurrencyPanel.add(fieldFirstAmount, BorderLayout.CENTER);
        btnExchange = new JButton();
        btnExchange.setLabel("Przelicz");
        btnExchange.setText("Przelicz");
        firstCurrencyPanel.add(btnExchange, BorderLayout.EAST);
        panelNorth = new JPanel();
        panelNorth.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        firstCurrencyPanel.add(panelNorth, BorderLayout.NORTH);
        labelFirstAmount = new JLabel();
        labelFirstAmount.setText("Kwota Do Przeliczenia:");
        panelNorth.add(labelFirstAmount);
        panelSwap = new JPanel();
        panelSwap.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelExchangePanel.add(panelSwap);
        btnSwapCurrencies = new JButton();
        btnSwapCurrencies.setText("<----->");
        panelSwap.add(btnSwapCurrencies, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        secondCurrencyPanel = new JPanel();
        secondCurrencyPanel.setLayout(new BorderLayout(0, 0));
        panelExchangePanel.add(secondCurrencyPanel);
        panelSecondNorth = new JPanel();
        panelSecondNorth.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        secondCurrencyPanel.add(panelSecondNorth, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Kwota Po Przeliczeniu:");
        panelSecondNorth.add(label1);
        fieldSecondAmount = new JTextField();
        fieldSecondAmount.setColumns(15);
        secondCurrencyPanel.add(fieldSecondAmount, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelExchangePanel;
    }
}
