package edu.dsoft.gui;

import edu.dsoft.ConverterController;
import edu.dsoft.Pair;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class CurrencySelectionPanel {
    protected JPanel selectionPanel;
    private JLabel labelFirstCurrency;
    private JComboBox comboFirstCurrency;
    private JLabel labelSecondCurrency;
    private JComboBox comboSecondCurrency;
    private JButton btnGetData;
    private JPanel pairSelectionPanel;
    private JPanel currenSelectedPanel;
    private JTextField labelCurrentPair;

    String[] currencyArray = {"USD", "EUR", "PLN", "JPY"};

    private String firstCode, secondCode;

    public CurrencySelectionPanel() {
        btnGetData.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (firstCode != null && secondCode != null) {
                    ConverterController.getInstance().createCurrencyPair(firstCode, secondCode);
                } else {
                    // TODO: 14.12.2022 Dodanie obsługi błędów związanych z brakiem wyboru waluty
                }
            }
        });
        addAllCodes(comboFirstCurrency, currencyArray);
        addAllCodes(comboSecondCurrency, currencyArray);
        comboFirstCurrency.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    firstCode = (String) (e.getItem());
                }
            }
        });
        comboSecondCurrency.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    secondCode = (String) (e.getItem());
                }
            }
        });
    }

    private void addAllCodes(JComboBox box, String[] options) {
        for (String s : options) {
            box.addItem(s);
        }
    }

    public void setCurrentSelectedPair(Pair p) {
        System.out.println("Para:\t" + p.toString());
        labelCurrentPair.setText(p.getPairName());
    }

    protected JPanel getSelectionPanel() {
        return selectionPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        selectionPanel = new JPanel();
        selectionPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 0));
        selectionPanel.setMaximumSize(new Dimension(600, 40));
        selectionPanel.setMinimumSize(new Dimension(600, 40));
        selectionPanel.setPreferredSize(new Dimension(600, 40));
        pairSelectionPanel = new JPanel();
        pairSelectionPanel.setLayout(new GridBagLayout());
        selectionPanel.add(pairSelectionPanel);
        pairSelectionPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 5), null, TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, null));
        labelFirstCurrency = new JLabel();
        labelFirstCurrency.setAlignmentX(0.5f);
        labelFirstCurrency.setText("Waluta 1");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 5, 0, 5);
        pairSelectionPanel.add(labelFirstCurrency, gbc);
        comboFirstCurrency = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 5, 0, 5);
        pairSelectionPanel.add(comboFirstCurrency, gbc);
        labelSecondCurrency = new JLabel();
        labelSecondCurrency.setText("Waluta 2");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 5, 0, 5);
        pairSelectionPanel.add(labelSecondCurrency, gbc);
        comboSecondCurrency = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 5, 0, 5);
        pairSelectionPanel.add(comboSecondCurrency, gbc);
        btnGetData = new JButton();
        btnGetData.setHideActionText(false);
        btnGetData.setText("Pobierz Dane");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 5, 0, 5);
        pairSelectionPanel.add(btnGetData, gbc);
        currenSelectedPanel = new JPanel();
        currenSelectedPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 0));
        currenSelectedPanel.setAlignmentX(0.5f);
        currenSelectedPanel.setAlignmentY(0.5f);
        selectionPanel.add(currenSelectedPanel);
        currenSelectedPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Aktualna Para:");
        label1.setVerifyInputWhenFocusTarget(false);
        label1.setVerticalAlignment(0);
        label1.setVerticalTextPosition(0);
        currenSelectedPanel.add(label1);
        currentSelectedFieldPanel = new JPanel();
        currentSelectedFieldPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        currentSelectedFieldPanel.setPreferredSize(new Dimension(300, 40));
        selectionPanel.add(currentSelectedFieldPanel);
        labelCurrentPair = new JTextField();
        labelCurrentPair.setColumns(7);
        labelCurrentPair.setEditable(false);
        labelCurrentPair.setEnabled(true);
        labelCurrentPair.setHorizontalAlignment(0);
        labelCurrentPair.setMaximumSize(new Dimension(150, 30));
        labelCurrentPair.setMinimumSize(new Dimension(150, 30));
        labelCurrentPair.setPreferredSize(new Dimension(83, 30));
        labelCurrentPair.setText("       ");
        currentSelectedFieldPanel.add(labelCurrentPair);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return selectionPanel;
    }

}
